name: amlmm
channels:
  - conda-forge
dependencies:
  - python=3.6
  - ipykernel
  - nb_conda_kernels
  - papermill
  - pip  
  - pip:
    - azure-cli
    - azureml-sdk[notebooks]==1.0.17
    - azure-storage-blob==12.0.0   
    - python-dotenv==0.10.4
